### ISSUE TITLE
Accord replacement by Math.NET Numerics

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [kkartavenka/AdaptiveEMA#1]
Hi,

thanks for your code. It's interesting!
Is it possible to replace all Accord code and references with Mathnet.Numerics?
Accord is outdated and no longer maintained.

regards
Tobias

**Comment by kkartavenka** [comment]
Hi, yes I was planning certain updates to the algorithm, including reducing external dependencies or at least updating to the most up-to-date

**Comment by kkartavenka** [comment]
Accord.Net is replaced with Mathnet.Numerics.

**Comment by ToGoOrNotToGo** [comment]
Very cool. Thanks!
